/*
 * Copyright (C) 2019 Ondrej Starek
 *
 * This file is part of OTest2.
 *
 * OTest2 is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OTest2 is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with OTest2.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <otest2/otest2.h>

#include <exception>
#include <iostream>
#include <stdexcept>

namespace OTest2 {

namespace SelfTest {

/**
 * @brief This suite tests the assertion functions
 */
TEST_SUITE(ExceptionsSuite) {
  TEST_CASE(MarkedTryCatch) {
    TEST_SIMPLE() {
      /* -- the exception happens */
      testTry {
        throw std::bad_exception();
      }
      testCatch(std::bad_exception&, exc_) {
        testAssertEqual(exc_.what(), "std::bad_exception");
      }

      /* -- no exception happens */
      testTry {
        /* -- don't throw anything */
      }
      testCatch(std::bad_exception&, exc_) {

      }

      /* -- different exception happens */
      testTry {
        throw std::invalid_argument("foo");
      }
      testCatch(std::bad_exception&, exc_) {

      }
    }
  }

  TEST_CASE(UnhandledException) {
    TEST_SIMPLE() {
      throw std::bad_exception();
    }
  }

  TEST_CASE(ExceptionFromCaseStartUp) {
    TEST_START_UP() {
      throw std::bad_exception();
    }

    TEST_SIMPLE() {

    }
  }

  TEST_CASE(ExceptionFromCaseTearDown) {
    TEST_TEAR_DOWN() {
      throw std::bad_exception();
    }

    TEST_SIMPLE() {

    }
  }
}

TEST_SUITE(ExceptionFromSuiteStartUp) {
  TEST_START_UP() {
    throw std::bad_exception();
  }
}

TEST_SUITE(ExceptionFromSuiteTearDown) {
  TEST_TEAR_DOWN() {
    throw std::bad_exception();
  }
}

} /* -- namespace SelfTest */

} /* -- namespace OTest2 */
